import React from "react";
import Head from "next/head";
import { FiSun } from 'react-icons/fi';
import { HiOutlineMoon } from 'react-icons/hi';

const Navbar = () => {
    return(
        <nav className="flex items-center justify-evenly p-4">
        <Head>
        <title>Job Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-xl">Home</h1>
        <h1 className="text-xl">Jobs </h1>
        <HiOutlineMoon  className="text-2xl"/>
        <h1 className="text-xl">Wallet</h1>
        </nav>
    )
}

export default Navbar