import React from "react";

const Navbar = () => {
    return(
        <nav>
        <Head>
        <title>Job Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        </nav>
    )
}

export default Navbar