import React from "react";
import Head from "next/head";
import { FiSun } from 'react-icons/fi';
import { HiOutlineMoon } from 'react-icons/hi';

const Navbar = (props) => {
    const {darkMode, toggleDarkMode} = props
    return(
        <nav className="flex items-center justify-evenly p-4">
        <Head>
        <title>Job Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@500;600&display=swap');
        </style>
        </Head>
        <h1 className="text-xl cursor-pointer">Home</h1>
        <h1 className="text-xl cursor-pointer">Jobs </h1>
        {
            darkMode ? <HiOutlineMoon className="text-2xl cursor-pointer" onClick={toggleDarkMode}/>
            : <FiSun className="text-2xl cursor-pointer" onClick={toggleDarkMode}/>
        }
        <h1 className="text-xl cursor-pointer">Wallet</h1>
        </nav>
    )
}

export default Navbar