import Head from 'next/head'
import React from 'react'

const Navbar = () => {
  return (
    <nav>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Shit is actually working</h1>
    </nav>
  )
}

export default Navbar