import Head from "next/head";
import React from "react";
import { FiSun } from "react-icons/fi";
import { IoMdMoon } from "react-icons/io";
import Image from 'next/image'
import logo from '../../assets/blog3.png'

const Navbar = (props) => {
  const { darkMode, setDarkMode, toggleModal } = props;

  const toggleDarkMode = () => {
    setDarkMode((prevMode) => !prevMode);
  };

  return (
    <nav className="text-white bg-gray-900  py-3 shadow-lg shadow-black-500/50 dark:bg-[#10172a] mb-2 dark:mb-0">
      <Head>
        <title>Blog Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex items-center justify-between px-8">
        <div className="flex items-center">
            <div className="max-w-[140px] mr-6">
                <Image src={logo} />
            </div>
          <h1 className="text-xl cursor-pointer dark:text-white">Home</h1>
        </div>

        <div className="flex px-4 ">
          {darkMode === false ? (
            <FiSun
              className="text-4xl cursor-pointer"
              onClick={toggleDarkMode}
            />
          ) : (
            <IoMdMoon
              className="text-4xl cursor-pointer text-white"
              onClick={toggleDarkMode}
            />
          )}

          <button
            className="bg-blue-500 cursor-pointer rounded-2xl px-3 mx-0 text-white ml-8"
            onClick={toggleModal}
          >
            + Add New
          </button>
        </div>
      </section>
    </nav>
  );
};

export default Navbar;
