import React from "react";
import Head from "next/head";
import { CgSun } from "react-icons/cg";
import { BsMoon } from "react-icons/bs";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const Navbar = (props) => {
  const { toggleDarkMode, darkMode } = props;

  return (
    <main className=" w-full">
      <Head>
        <title>Voting dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Lato&family=Poppins:wght@400;500;700&family=Roboto:wght@300;900&display=swap');
        </style>
      </Head>
      <nav
        className={`py-4  ${
          darkMode
            ? `bg-gradient-to-r from-sky-600 to-indigo-600`
            : `bg-gradient-to-r from-cyan-400 to-blue-500`
        } `}
      >
        <div className="flex items-center justify-around">
          {darkMode ? (
            <BsMoon
              className="cursor-pointer text-4xl mr-6 text-white"
              onClick={toggleDarkMode}
            />
          ) : (
            <CgSun
              className="cursor-pointer text-4xl mr-6 text-white"
              onClick={toggleDarkMode}
            />
          )}
          <h3 className="text-4xl text-white">Decentralized Voting App</h3>
          <ConnectButton
            showBalance={false}
            accountStatus={{
              smallScreen: "avatar",
              largeScreen: "full",
            }}
          />
        </div>
      </nav>
    </main>
  );
};
export default Navbar;