import React from "react";
import Head from "next/head";
import { FiSun } from "react-icons/fi";
import { IoMdMoon } from "react-icons/io";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const Navbar = (props) => {
  const { darkMode, toggleDarkMode } = props;

  return (
    <main>
      <Head>
        <title>Vending Machine!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Lato&family=Poppins:wght@400;500;700&family=Roboto:wght@300;900&display=swap');
        </style>
      </Head>
      <nav
        className={`py-4 ${
          darkMode && `bg-gradient-to-r from-sky-600 to-indigo-600`
        } bg-orange-300 `}
      >
        <div className="flex items-center justify-around">
          {darkMode ? (
            <IoMdMoon
              className="cursor-pointer text-4xl mr-6 text-white"
              onClick={toggleDarkMode}
            />
          ) : (
            <FiSun
              className="cursor-pointer text-4xl mr-6"
              onClick={toggleDarkMode}
            />
          )}
          <h3 className="text-4xl pl-5 text-white">Vending Machine Dapp</h3>
          <ConnectButton
            showBalance={false}
            accountStatus={{
              smallScreen: "avatar",
              largeScreen: "full",
            }}
          />
        </div>
      </nav>
    </main>
  );
};

export default Navbar;
